---
:editor: vim
:thread_by_subject: true
:edit_signature: true
:ask_for_from: false
:ask_for_to: true
:ask_for_cc: true
:ask_for_bcc: false
:ask_for_subject: true
:account_selector: true
:confirm_no_attachments: true
:confirm_top_posting: true
:jump_to_open_message: true
:discard_snippets_from_encrypted_messages: false
:load_more_threads_when_scrolling: true
:default_attachment_save_dir: ''
:sent_source: maildir:/home/chrcoe/.mail/gmail-test/sent
:archive_sent: true
:poll_interval: 30
:wrap_width: 80
:slip_rows: 0
:col_jump: 2
:stem_language: english
:sync_back_to_maildir: true
:continuous_scroll: false
:always_edit_async: false
:accounts:
  :default:
    :name: Chris Coe
    :email: chrcoe.test@gmail.com
    :alternates: []
    :sendmail: "/usr/bin/msmtp -t --read-envelope-from"
    :signature: "/home/chrcoe/.sup/signature"
    :gpgkey: '63C72A388E56905BDD669E0099CFE0D4E04C8F6A'
:time_mode: 
