#! /bin/bash

sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

# cleanup after oh-my-zsh to use the one in my dotfiles
rm /home/chrcoe/.zshrc

# cd /home/code
# git clone https://github.com/powerline/fonts.git

cd /home/chrcoe/.dotfiles
script/bootstrap

/bin/zsh
