#! /bin/bash

# install oh-my-zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

# cleanup after oh-my-zsh to use the one in my dotfiles without being prompted to overwrite it
rm /home/chrcoe/.zshrc

# cd /home/chrcoe/code
# git clone https://github.com/powerline/fonts.git

# bootstrap all dotfiles ...
/home/chrcoe/.dotfiles/script/bootstrap

# install powerline symbols...
wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf
mv PowerlineSymbols.otf ~/.fonts/
mkdir -p .config/fontconfig/conf.d
fc-cache -vf ~/.fonts/
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/


/bin/zsh
