#!/bin/zsh

# take screenshot
scrot /tmp/screen_locked.png
# blur it and overwrite original for security
# convert /tmp/screen_locked.png -blur 0x3 /tmp/screen_locked.png
convert /tmp/screen_locked.png -blur 0x6 /tmp/screen_locked.png
# lock the screen using this image
i3lock -i /tmp/screen_locked.png
# turn the display off after a 60 second delay
sleep 60; pgrep i3lock && xset dpms force off
